### PR TITLE
Add sales-dashboard demo

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board-demo/8)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 7 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/common/demo-area.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8#-KgDlwoJ0FGzPd47TDku:-KgDlwoJ0FGzPd47TDkv:baie7mb) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/0295c4365d07fe93536a64655ab1036e73674d27/src/common/demo-area.html#L15)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>       :host ::slotted(*) {
>         display: block;
>         overflow-x:hidden;
>       }
</details>

is this needed?
the hack for highcharts should be on the chart container only
demo seems to work correctly without this, but I might be missing something

---

*[src/sales-dashboard/demo-element.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8#-KgDm0AxZ2ybgyIkx18K:-KgDm0AxZ2ybgyIkx18L:bctxdxz) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/0295c4365d07fe93536a64655ab1036e73674d27/src/sales-dashboard/demo-element.html#L1)):*
> ```HTML
> <link rel="import" href="../../bower_components/polymer/polymer-element.html">
> ```

is this file needed?

---

*[src/sales-dashboard/sales-dashboard.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8#-KgDmBxbFScToZLzHuhv:-KgDmBxbFScToZLzHuhw:bcalue) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/0295c4365d07fe93536a64655ab1036e73674d27/src/sales-dashboard/sales-dashboard.html#L15)):*
> <link rel="import" href="../../bower_components/vaadin-charts/vaadin-line-chart.html">

import not needed

---

*[src/sales-dashboard/sales-dashboard.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8#-KgDmHfpGeY7DcDx57-O:-KgDmHfpGeY7DcDx57-P:b-vsiq5q) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/0295c4365d07fe93536a64655ab1036e73674d27/src/sales-dashboard/sales-dashboard.html#L31)):*
>         /*display: block;*/
>  
>         padding: 10px;
>         overflow-x: hidden;

looks like changes here are not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8)*

**Comment by rogozinds** [comment]
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/sales-dashboard/demo-element.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8#-KgDm0AxZ2ybgyIkx18K:-KgK7Of_o4vdt9cbcl05:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/0295c4365d07fe93536a64655ab1036e73674d27/src/sales-dashboard/demo-element.html#L1)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

is this file needed?
</blockquote></details>

Done.

---

*[src/sales-dashboard/sales-dashboard.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8#-KgDmBxbFScToZLzHuhv:-KgK7abkPNSAL7w3GHjW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/0295c4365d07fe93536a64655ab1036e73674d27/src/sales-dashboard/sales-dashboard.html#L15)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> <link rel="import" href="../../bower_components/vaadin-charts/vaadin-line-chart.html">

import not needed
</blockquote></details>

Done.

---

*[src/sales-dashboard/sales-dashboard.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8#-KgDmHfpGeY7DcDx57-O:-KgK8D2m71a-Snoby9ts:bn933f1) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/0295c4365d07fe93536a64655ab1036e73674d27/src/sales-dashboard/sales-dashboard.html#L31)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         /*display: block;*/
>  
>         padding: 10px;
>         overflow-x: hidden;

looks like changes here are not needed
</blockquote></details>

Right, it's using card class to style these

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8)*

**Comment by rogozinds** [comment]
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/common/demo-area.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8#-KgDlwoJ0FGzPd47TDku:-KgK8MpMlD0KzH14wfPd:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/0295c4365d07fe93536a64655ab1036e73674d27/src/common/demo-area.html#L15)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>       :host ::slotted(*) {
>         display: block;
>         overflow-x:hidden;
>       }

is this needed?
the hack for highcharts should be on the chart container only
demo seems to work correctly without this, but I might be missing something
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8)*

**Comment by alvarezguille** [comment]
Reviewed 4 of 4 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/8)*

**Pull request merged**
