### PR TITLE
Add example area.

### PR DESCRIPTION
**Pull request by rogozinds**
Add common classes for demo.
Edited Raw types demo.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board-demo/3)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 46 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-KesVrlM7RUSA3jJpDHu:-KesVrlOHUcJKiSdlF76:b-xwov3x) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/9f25c4f245b03d9a6d9d344ac2a0440e0fcd7304/bower.json#L46)):*
> ```JSON
>     "iron-resizable-behavior":"#2.0-preview"
>   }
> }
> ```

cleaned a bit the new dependencies and resolutions, got to

  "dependencies": {
    "app-layout": "PolymerElements/app-layout#2.0-preview",
    "app-route": "PolymerElements/app-route#2.0-preview",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#2.0-preview",
    "iron-icon": "PolymerElements/iron-icon#2.0-preview",
    "iron-iconset-svg": "PolymerElements/iron-iconset-svg#2.0-preview",
    "iron-localstorage": "PolymerElements/iron-localstorage#2.0-preview",
    "iron-media-query": "PolymerElements/iron-media-query#2.0-preview",
    "iron-pages": "PolymerElements/iron-pages#2.0-preview",
    "iron-selector": "PolymerElements/iron-selector#2.0-preview",
    "paper-button": "#2.0-preview",
    "paper-icon-button": "PolymerElements/paper-icon-button#2.0-preview",
    "polymer": "Polymer/polymer#^2.0",
    "vaadin-board": "vaadin/vaadin-board#master",
    "vaadin-icons": "v2.0.0",
    "vaadin-split-layout": "v1.1.0-alpha1",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.0-rc.5"
  },
  "devDependencies": {
    "web-component-tester": "6.0.0-prerelease.5"
  },
  "private": true,
  "resolutions": {
    "iron-iconset-svg": "2.0-preview",
    "iron-icon": "2.0-preview",
    "webcomponentsjs": "^1.0.0-rc.5",
    "polymer": "^2.0",
    "iron-resizable-behavior": "2.0-preview",
    "iron-flex-layout": "2.0-preview",
    "iron-meta": "2.0-preview"
  }

---

*[src/common/demo-app.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-KesWI1yu8hi1YCOSeLg:-KesWI1yu8hi1YCOSeLh:be46jf9) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/9f25c4f245b03d9a6d9d344ac2a0440e0fcd7304/src/common/demo-app.html#L9)):*
> demo-app

can we rename this to something more component and less app?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3)*

**Comment by rogozinds** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 46 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-KesVrlM7RUSA3jJpDHu:-Kf5kXx_JBIxc1a4wxIf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/9f25c4f245b03d9a6d9d344ac2a0440e0fcd7304/bower.json#L46)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

cleaned a bit the new dependencies and resolutions, got to

  "dependencies": {
    "app-layout": "PolymerElements/app-layout#2.0-preview",
    "app-route": "PolymerElements/app-route#2.0-preview",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#2.0-preview",
    "iron-icon": "PolymerElements/iron-icon#2.0-preview",
    "iron-iconset-svg": "PolymerElements/iron-iconset-svg#2.0-preview",
    "iron-localstorage": "PolymerElements/iron-localstorage#2.0-preview",
    "iron-media-query": "PolymerElements/iron-media-query#2.0-preview",
    "iron-pages": "PolymerElements/iron-pages#2.0-preview",
    "iron-selector": "PolymerElements/iron-selector#2.0-preview",
    "paper-button": "#2.0-preview",
    "paper-icon-button": "PolymerElements/paper-icon-button#2.0-preview",
    "polymer": "Polymer/polymer#^2.0",
    "vaadin-board": "vaadin/vaadin-board#master",
    "vaadin-icons": "v2.0.0",
    "vaadin-split-layout": "v1.1.0-alpha1",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.0-rc.5"
  },
  "devDependencies": {
    "web-component-tester": "6.0.0-prerelease.5"
  },
  "private": true,
  "resolutions": {
    "iron-iconset-svg": "2.0-preview",
    "iron-icon": "2.0-preview",
    "webcomponentsjs": "^1.0.0-rc.5",
    "polymer": "^2.0",
    "iron-resizable-behavior": "2.0-preview",
    "iron-flex-layout": "2.0-preview",
    "iron-meta": "2.0-preview"
  }
</blockquote></details>

Done.

---

*[src/common/demo-app.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-KesWI1yu8hi1YCOSeLg:-Kf5lXrli0FNUKFZIhcB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/9f25c4f245b03d9a6d9d344ac2a0440e0fcd7304/src/common/demo-app.html#L9)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> demo-app

can we rename this to something more component and less app?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 7 files at r1, 1 of 4 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 5 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-Kf7Pgipi51gnNqoLA8E:-Kf7PgiqJ405e0MYMbGP:bsbe83m) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/2dcc592af2b60568200843e3c88cea3099a06ed5/bower.json#L5)):*
>   "dependencies": {


remove duplicated

---

*[src/common/right-part-area.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-KesWI1yu8hi1YCOSeLg:-Kf7QVj463hSoV452VnU:b-naoesj) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/9f25c4f245b03d9a6d9d344ac2a0440e0fcd7304/src/common/right-part-area.html#L9)):*
> right-part-area

we can check tomorrow, not convinced by the new name, but let's not make it an issue

---

*[src/common/right-part-area.html, line 78 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-Kf7Q4vEQOrI8AhfiANR:-Kf7Q4vEQOrI8AhfiANS:b-thq30w) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/2dcc592af2b60568200843e3c88cea3099a06ed5/src/common/right-part-area.html#L78)):*
> DemoApp

traces of demoapp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3)*

**Comment by rogozinds** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 46 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-KesVrlM7RUSA3jJpDHu:-KfAmiF1VKqL4glB8nBJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/9f25c4f245b03d9a6d9d344ac2a0440e0fcd7304/bower.json#L46)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[bower.json, line 5 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-Kf7Pgipi51gnNqoLA8E:-KfAmhW-gxMxRsXbeurt:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/2dcc592af2b60568200843e3c88cea3099a06ed5/bower.json#L5)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>   "dependencies": {


remove duplicated
</blockquote></details>

Done.

---

*[src/common/right-part-area.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-KesWI1yu8hi1YCOSeLg:-KfB7y84yrg_WomrTrTD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/9f25c4f245b03d9a6d9d344ac2a0440e0fcd7304/src/common/right-part-area.html#L9)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> right-part-area

we can check tomorrow, not convinced by the new name, but let's not make it an issue
</blockquote></details>

Done.

---

*[src/common/right-part-area.html, line 78 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3#-Kf7Q4vEQOrI8AhfiANR:-KfB7yWw9sSodk72LM1s:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/2dcc592af2b60568200843e3c88cea3099a06ed5/src/common/right-part-area.html#L78)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> DemoApp

traces of demoapp
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 5 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/3)*

**Pull request merged**
