### PR TITLE
Fix stacked bar chart height in safari

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board-demo/14)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sales-dashboard/mid-column-chart.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14#-KgxhejrsWiaGOqHeOsB:-KgxhejrsWiaGOqHeOsC:b2vbr3q) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/fcad354308766a30db0ae6363c4a43276fbb63fb/src/sales-dashboard/mid-column-chart.html#L9)):*
> style="flex:1">
Let's not use shorthand, there is a problem with IE11
https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored
Let's use full version flex: 1, 0, 0%;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14)*

**Comment by alvarezguille** [comment]
*[src/sales-dashboard/mid-column-chart.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14#-KgxhejrsWiaGOqHeOsB:-Kgxj6zpR7g06FuOhlye:bwfx9kj) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/fcad354308766a30db0ae6363c4a43276fbb63fb/src/sales-dashboard/mid-column-chart.html#L9)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> style="flex:1">
Let's not use shorthand, there is a problem with IE11
https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored
Let's use full version flex: 1, 0, 0%;
</blockquote></details>

agreed, done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14)*

**Comment by rogozinds** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sales-dashboard/mid-column-chart.html, line 9 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14#-KgxluvjEI9QBgRI90H5:-KgxluvjEI9QBgRI90H6:b-xagltn) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/99fd4592d9cf04bcf38c29674124c92ea4d4bea5/src/sales-dashboard/mid-column-chart.html#L9)):*
> 1 1 0;
I don't know how it's relevant, but the same doc says:
"When using the flex shorthand, always include a unit in the flex-basis portion. For example: 1 0 0%."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14)*

**Comment by alvarezguille** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sales-dashboard/mid-column-chart.html, line 9 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14#-KgxluvjEI9QBgRI90H5:-Kgxn-755_nX_CXA7eDw:b-2d5r) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/99fd4592d9cf04bcf38c29674124c92ea4d4bea5/src/sales-dashboard/mid-column-chart.html#L9)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> 1 1 0;
I don't know how it's relevant, but the same doc says:
"When using the flex shorthand, always include a unit in the flex-basis portion. For example: 1 0 0%."
</blockquote></details>

added the workaround for IE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14)*

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/14#-:-KgxnAsb2_Nk34HWxEkI:bnfp4nl)*

**Pull request merged**
