### PR TITLE
Load Vaadin customer chat (when hosted on demo.vaadin.com)

### PR DESCRIPTION
**Pull request by Haprog**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board-demo/50)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/50)*

**Comment by Haprog** [comment]
If you want to test locally that this works as intended, you need to comment out this line https://github.com/Haprog/vaadin-board-demo/blob/bc81b6eefea88f9249a02c3858ac6963c7c464c3/src/customer-chat.js#L2
which checks if you are running on `demo.vaadin.com` or not and you must not be in the Vaadin internal network (otherwise the chat will not load). You might also need to be logged out of your employee profile at vaadin.com (or test with incognito mode).

If you want you could also make a temporary entry in you `/etc/hosts` file for `127.0.0.1 demo.vaadin.com` to simulate running it on the target domain without having to comment out the domain check in the JS code.

With these conditions you should see the chat button on the bottom right of the browser viewport when running this project locally

**Comment by Haprog** [comment]
It will look like this 
image

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/50)*

**Comment by rogozinds** [comment]
Merged by another patch.

**Pull request closed without merging**
