### PR TITLE
use the fonts from the new brand visual style

### PR DESCRIPTION
**Pull request by vlukashov**
Key changes:
 - add 2 fonts into this repo (Montserrat and Source Code Pro)
 - replace the Open Sans with Montserrat all over the code base
 - use Source Code Pro for code snippets

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board-demo/60)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[src/sales-dashboard/top-chart.html, line 14 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60#-KpoLnXSNEMs8LBUhNzA:-KpoLnXSNEMs8LBUhNzB:b-a4o3cr) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/4750735a64c016a7a927150492986d84afa606c2/src/sales-dashboard/top-chart.html#L14)):*
> font-size: 14px;

I was wondering about this, but it's not used anywhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60)*

**Comment by alvarezguille** [comment]
Reviewed 12 of 18 files at r1, 4 of 6 files at r3.
Review status: 16 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[polymer.json, line 13 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60#-KpoK-Y3mAoBwlh3aiWH:-KpoK-Y3mAoBwlh3aiWI:b-4w5lfq) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/4750735a64c016a7a927150492986d84afa606c2/polymer.json#L13)):*
> "fonts/**/*",

should we have an extension filter here? to avoid packaging and serving the readme

---

*[src/row-types/demo-element.html, line 9 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60#-KpoKDrwajDhU8xqJrbO:-KpoKDrwajDhU8xqJrbP:b-omqyil) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/4750735a64c016a7a927150492986d84afa606c2/src/row-types/demo-element.html#L9)):*
> font-size: 13px;

this shouldn't be montserrat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60)*

**Comment by vlukashov** [comment]
Review status: 13 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[polymer.json, line 13 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60#-KpoK-Y3mAoBwlh3aiWH:-KpoTSr51RlsAvOnyW0w:b-7ql1td) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/4750735a64c016a7a927150492986d84afa606c2/polymer.json#L13)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> "fonts/**/*",

should we have an extension filter here? to avoid packaging and serving the readme
</blockquote></details>

fixed

---

*[src/row-types/demo-element.html, line 9 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60#-KpoKDrwajDhU8xqJrbO:-KpoSSzpey1PcxUZg4Ht:b-fiypjk) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/4750735a64c016a7a927150492986d84afa606c2/src/row-types/demo-element.html#L9)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> font-size: 13px;

this shouldn't be montserrat
</blockquote></details>

set on the `demo-area > #content` level

---

*[src/sales-dashboard/top-chart.html, line 14 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60#-KpoLnXSNEMs8LBUhNzA:-KpoSdKtnYHvC46ynxOT:b-hfpv0l) ([raw file](https://github.com/vaadin/vaadin-board-demo/blob/4750735a64c016a7a927150492986d84afa606c2/src/sales-dashboard/top-chart.html#L14)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> font-size: 14px;

I was wondering about this, but it's not used anywhere
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 18 files at r1, 1 of 6 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board-demo/60)*

**Pull request merged**
